PR-new-logo-orizontal (1).svg
# **Lab01PR. Introducere in Data Science**

# Scopul Laboratorului

In cadrul primului laborator vom exersa manipularea si extragerea informatiilor din dataset-uri folosind biblioteci din limbajul Python.


### *Atentie!* Inainte de a incepe laboratorul descarcati dataset-urile de la link-ul următor https://drive.google.com/file/d/150MHlLzas_lvvDHxNDxQFZT2E2RTd441/view?usp=sharing si incarcati-le la Files in Colab in folderul root.


# Cuvinte-Cheie

*   Numpy
*   Pandas
*   Series
*   DataFrame
*   Data Cleaning

# Utilizari in Lumea Reala

*   analiza metricilor unui sistem/unei aplicatii (performante, erori)
*   meteorologie (vizualizare, predictii)
*   statistici in domeniul medical (de exemplu, rata de imbolnavire cu un virus la persoanele vacinate fata de cele vaccinate)
*   observarea tendintelor sociale/politice/financiare (corelarea studiilor sau a categoriei de varsta cu preferintele unui individ)
*   procesarea limbajului natural
*   analiza feedback-ului consumatorilor (pentru imbunatatirea serviciilor)
*   analiza retelelor sociale

![picture](https://drive.google.com/uc?export=view&id=1bUWb8LXnkmviWqnCRbNPSjC0L3e7m49d)


# Python Memento

Amitim cateva facilitati oferite de limbajul Python:

### List Comprehension
Creeaza o lista pornind de la elementele unei alte liste intr-un one-liner.

In [281]:
import numpy
integers = [x for x in list(range(0, 10))]
print(integers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Slicing
Extrage un fragment contiguu dintr-o lista.


*Atentie!* Un slice [n:m] va intoarce elementele listei pornind *de la indexul n pana la indexul m-1*, intrucat indexarea in Python incepe de la 0.

In [282]:
half = integers[:5]
print(half)

[0, 1, 2, 3, 4]


In [283]:
mid = integers[4:6]
print(mid)

[4, 5]


In [284]:
all = integers[:]
print(all)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Lambdas

Lambdas sunt functii anonime scrise ca one-liner. Pot primi oricate argumente si pot fi date drept parametru pentru functionale.

In [285]:
foo = lambda x: x ** 2 + 3 * x + 1
foo(5)

41

### Functional Programming

# Optional: Good to know

### Filter

In [286]:
filter(lambda x: x % 2 == 1, integers)


In [287]:
odd = list(filter(lambda x: x % 2 == 1, integers))
print(odd)

[1, 3, 5, 7, 9]


### Map

In [288]:
squares = list(map(lambda x: x ** 2, integers))
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Reduce

In [289]:
from functools import reduce
sum = reduce(lambda x, y: x + y, integers)
print(sum)
initial_value = 10
sum = reduce(lambda x, y: x + y, integers, initial_value)
print(sum)

45
55


# NumPy

NumPy este o biblioteca pentru limbajul Python specializata pe operatii matematice (structuri de date dedicate, vectorizari, functii optimizate). Ofera instrumente de creare, stocare si manipulare a informatiilor, ceea ce faciliteaza integrarea cu numeroase baze de date.

## Programare orientata pe Array-uri

Elementul de baza in manipularea datelor folosind NumPy este np.array. Acesta poate fi creat fie pornind de la una sau mai multe liste, fie folosind functii speciale.

In [290]:
import numpy as np

# array uni-dimensional de 5 elemente
uni = np.array([0, 1, 2, 3, 4])
print(uni)
print(type(uni))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [291]:
# array multi-dimensional, cu 2 dimensiuni, fiecare avand 4 elemente
multi = np.array([[1, 1, 2, 3], [5, 8, 13, 21]])
print(multi)

[[ 1  1  2  3]
 [ 5  8 13 21]]


Pentru a afla *dimensiunile unui np.array*, putem folosi urmatoarele atribute:
*   *shape*: forma array-ului (distributia elementelor pe linii si coloane)
*   *ndim*: numarul de dimensiuni
*   *size*: numarul total de elemente din array

In [292]:
print("Array shapes:")
print(uni.shape)
print(multi.shape)
print("\n")

print("Array dimensions:")
print(uni.ndim)
print(multi.ndim)
print("\n")

print("Array size:")
print(uni.size)
print(multi.size)

Array shapes:
(5,)
(2, 4)


Array dimensions:
1
2


Array size:
5
8


Cum putem adauga o noua dimensiune la un np.array?

Exista doua variante: \
&emsp; - fie prin apelul metodei reshape careia ii dam drept parametrii *shape*-urile pe care ni le dorim sa le aiba *ndarray*-ul nostru \
&emsp; - fie prin apelul lui np.newaxis in interiorul [] care va adauga o noua dimensiune cu marimea 1 in pozitia in care este pus apelul; acest np.newaxis este doar un alias pentru *None*

In [293]:
uni_reshaped = uni.reshape(5, 1)
print(uni_reshaped.shape)

(5, 1)


In [294]:
uni_reshaped = uni[:, np.newaxis]
print(uni_reshaped.shape)

(5, 1)


In [295]:
uni_reshaped = uni[:, None]
print(uni_reshaped.shape)

(5, 1)


In [296]:
# array multi-dimensional generat cu numere random:
# np.random.rand(dim_no, dim_size)
np.random.rand(2, 4)

array([[0.92202185, 0.19057756, 0.74758988, 0.81988586],
       [0.59815999, 0.83630843, 0.19955685, 0.89598464]])

**Observatie**: In momentul generarii de numere aleatore folosind este recomandata folosirea unui *random seed*. Utilitatea acestui *random seed* rezida din dorinta noastra de a avea rezultate replicabile si de catre altii in momentul in care realizam experimente, astfel incat sa nu lucram pe numere diferite la rulari diferite. Singura conditie ce trebuie respectata de catre acest *random seed* este ca el sa nu fie aleatoriu la randul sau.

In [297]:
# array generat printr-un interval si un pas:
# np.arrange(start, stop, step)
third = np.arange(0, 21, 3)
print(third)

[ 0  3  6  9 12 15 18]


In [298]:
# interval si un numar de elemente distribuite simetric intr-un spatiu liniar:
# np.linspace(start, stop, elem_no)
np.linspace(0, 10, 9)


array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Functii Statistice si de Agregare


# Optional: Good to know

In [299]:
neg = [x for x in range(-10, 0)]
pos = [x for x in range(1, 11)]
arr = np.array([neg, pos])
print(arr)

[[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
 [  1   2   3   4   5   6   7   8   9  10]]


###    *Media Aritmetica: np.mean()*



In [300]:
# media pe axa liniilor
print(np.mean(arr, axis=0))

[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]


In [301]:
# media pe axa coloanelor
print(np.mean(arr, axis=1))

[-5.5  5.5]


In [302]:
# media tuturor elementelor
print(np.mean(arr))

0.0


### *Deviatia Standard:   np.std()*

*Reminder*: deviatia standard indica dispersia unui set de date relativ la media elementelor sale

    std = sqrt(mean(x)), unde x = abs(arr - arr.mean())**2


In [303]:
np.std(arr)

6.2048368229954285

In [304]:
np.std(arr, axis=0)

array([5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5])

In [305]:
np.std(arr, axis=1)

array([2.87228132, 2.87228132])

### *Suma, Produs: np.sum(), np.prod()*

In [306]:
np.sum(arr)

0

In [307]:
np.sum(arr, axis=0)

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [308]:
np.sum(arr, axis=1)

array([-55,  55])

In [309]:
np.prod(arr, axis=0)

array([-10, -18, -24, -28, -30, -30, -28, -24, -18, -10])

### *Min, Max: np.min(), np.max()*

In [310]:
np.min(arr)

-10

In [311]:
np.max(arr, axis=1)

array([-1, 10])

### *Min index, Max index: np.argmin(), np.argmax()*

In [312]:
np.argmin(arr)

0

In [313]:
np.argmax(arr, axis=1)

array([9, 9])

## Vectorizari

In contextul limbajelor high-level (precum Python, MATLAB, R), vectorizarea descrie utilizarea codului optimizat si pre-compilat pentru a realiza operatii asupra unor secvente de date. Acest lucru presupune executia in-place a operatiei asupra tuturor elementelor colectiei, fara a mai fi nevoie de o iteratie explicita.

Putem observa eficienta vectorizarii prin aplicarea functiei sum() in urmatorul exemplu:

In [314]:
import timeit

rand_arr = np.random.rand(30, 30)
rand_arr_vect = rand_arr
rand_arr_iter = rand_arr

def add_vect(arr):
  sum = np.sum(arr)

def add_iter(arr):
  sum = 0
  for num in arr:
    sum += num

In [315]:
%timeit add_vect(rand_arr_vect)

5.84 µs ± 368 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [316]:
%timeit add_iter(rand_arr_iter)

29.9 µs ± 773 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Indexare Booleana
Daca dorim sa accesam doar elementele care respecta o anumita conditie, putem folosi indexarea booleana.

Aceasta presupune crearea unei *masti booleene* (ce verifica pentru fiecare element conditia data si indica True sau False in dreptul fiecarui index, daca aceasta este verificata sau nu), Rezultatul mastii este folosit ulterior drept index pentru gasirea valorilor cautate.

Mastile booleene functioneaza pe array-uri continand orice tip de date (ex. numerice, string, bool).

In [317]:
arr = np.array([[-10,8,-6,4],
              [-2,0,2,-4],
              [6,-8,10,-12]])
print(arr)

[[-10   8  -6   4]
 [ -2   0   2  -4]
 [  6  -8  10 -12]]


Sa presupunem ca dorim sa extragem doar elementele pozitive din array.

In [318]:
# cream o masca pentru a gasi pozitiile ce respecta conditia
mask = arr >= 0
print(mask)

[[False  True False  True]
 [False  True  True False]
 [ True False  True False]]


In [319]:
# extragem elementele de pe pozitiile marcate cu True in masca
pos = arr[mask]
print(pos)

[ 8  4  0  2  6 10]


## Slicing

NumPy ofera posibilitatea de a extrage o vedere dintr-un array multidimensional prin slicing, similar cu cel din cazul listelor.

In [320]:
arr = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

# primul slice extrage liniile, iar cel de-al doilea coloanele cu indecsii specificati
print(arr[1:3, 2:5])

[[17 18 19]
 [22 23 24]]


# Pandas

Pandas este o biblioteca pentru limbajul Python specializata pe lucrul cu date, construita peste NumPy. Datorita facilitatilor pe care le ofera, este extrem de utila in preprocesarea, analiza, si vizualizarea datelor, precum si in analiza statistica sau machine learning.

## Series

Un Pandas Series este un array *unidimensional* (sau, mai simplu, o coloana) care poate contine orice tip de date.

Array-ul este *indexat* fie prin valori numerice, fie prin label-uri nominale.

### Cum putem crea Pandas Series?

#### 1. Pornind de la o *lista*

In [321]:
import numpy as np
import pandas as pd

topics = ['Data Science', 'Networking', 'Machine Learning', 'Bioinformatics', 'Cyber security', None]
pd.Series(topics)

0        Data Science
1          Networking
2    Machine Learning
3      Bioinformatics
4      Cyber security
5                None
dtype: object

#### 2. Pornind de la un *dictionar*

In [322]:
students_topics = {'Jack' : 'Networking',
                   'Chloe' : 'Machine Learning',
                   'Frank' : 'Cyber security',
                   'Barbara' : 'Bioinformatics'}
s = pd.Series(students_topics)
print(s)
print(s.index)

Jack             Networking
Chloe      Machine Learning
Frank        Cyber security
Barbara      Bioinformatics
dtype: object
Index(['Jack', 'Chloe', 'Frank', 'Barbara'], dtype='object')


#### 3. Pornind de la *o lista de valori si o lista de indecsi*

In [323]:
s = pd.Series(['Data Science', 'Bioinformatics', 'Networking'], index=['Alice', 'Claire', 'John'])
print(s)
print(s.index)

Alice       Data Science
Claire    Bioinformatics
John          Networking
dtype: object
Index(['Alice', 'Claire', 'John'], dtype='object')


### Cum accesam datele din Pandas Series?


#### 1. **iloc**: prin pozitia indexului in cadrul Series

In [324]:
s.iloc[1]

'Bioinformatics'

#### 2. **loc**: prin valoarea indexului

In [325]:
s.loc['Claire']

'Bioinformatics'

#### Conventie
Pentru a creste lizibilitatea codului, biblioteca Pandas foloseste o conventie de indexare:
 * daca vom accesa un element folosind un index *de tip intreg*, accesarea va fi echivalenta cu cea folosind atributul *iloc*
 * daca vom accesa un element folosind un index *de tip obiect*, accesarea va fi echivalenta cu cea folosind atributul *loc*

In [326]:
s[1]

/tmp/ipykernel_8927/878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]


'Bioinformatics'

In [327]:
s['Claire']

'Bioinformatics'

*Atentie!* Accesarea folosind un index *de tip intreg* poate fi inselatoare. Astfel, daca indecsii din Series sunt *de tip intreg*, in momentul accesarii pot aparea erori cauzate de faptul ca index-ul pe care dorim sa il folosim nu se afla in Series. Spre exemplu:

In [328]:
s = pd.Series({20: 'John',
               21: 'Claire',
               22: 'Chloe'})
s[0]

KeyError: 0

Pentru a nu ne lovi de aceasta eroare vom folosi atributul iloc pentru a accesa primul element din Series.

In [ ]:
s.iloc[0]

'John'

## DataFrame

DataFrame este structura cea mai folosita din Pandas.

Reprezinta un array *bidimensional* indexat (numeric sau nominal), in care o linie indica valori pentru o anumita intrare in setul de date, iar o coloana marcheaza elementul masurat. Astfel, valorile de pe o linie *pot* avea tipuri de date diferite, insa cele de pe o coloana *trebuie* sa fie omogene.

### Cum putem crea un DataFrame?

#### 1. Pornind de la un *dictionar* / o *lista de dictionare*

In [ ]:
import pandas as pd
import numpy as np

# dictionar
subjects = {"Subject": ["Computer Programming", "Data Structures"],\
            "Credits": ["5", "5"]}
df = pd.DataFrame(subjects)
df


Subject Credits
0  Computer Programming       5
1       Data Structures       5

In exemplul precedent, indecsii iau automat valori numerice pornind de la 0.

Avem insa posibilitatea de a seta indexul dataframe-ului *la momentul crearii* prin argumentul ***index=***:

In [ ]:
df = pd.DataFrame(subjects, index=["S1", "S2"])
df

Subject Credits
S1  Computer Programming       5
S2       Data Structures       5

Indexul mai poate fi setat la o coloana existenta folosind ***.set_index("column_name")***:

In [ ]:
# lista de dictionare
students = [{"Name": "Alice", "Subject": "Computer Programming", "Score": 90},\
            {"Name": "Bob", "Subject": "Computer Programming", "Score": 88}]
df = pd.DataFrame(students)
df.set_index("Name")

Subject  Score
Name                              
Alice  Computer Programming     90
Bob    Computer Programming     88

Putem reseta indecsii la valorile initiale cu ajutorul ***.reset_index()***:

In [ ]:
df.reset_index()
df

Name               Subject  Score
0  Alice  Computer Programming     90
1    Bob  Computer Programming     88

#### 2. Pornind de la un *NumPy ndarray*

In [ ]:
students = np.array([["", 'Subject', 'Score'],
                ["Alice", "Computer Programming", 90],
                ["Bob", "Computer Programming", 88]])

df = pd.DataFrame(data=students[1:, 1:],\
                  index=students[1:, 0],\
                  columns=students[0, 1:])
df

Subject Score
Alice  Computer Programming    90
Bob    Computer Programming    88

#### 3. Pornind de la Pandas *Series*

In [ ]:
# creare a unei pd.Series pornind de la o lista
subjects = pd.Series(["Computer Programming", "Data Structures",\
                      "OOP", "Programming Paradigms"])
subjects

0     Computer Programming
1          Data Structures
2                      OOP
3    Programming Paradigms
dtype: object

In [ ]:
df = pd.DataFrame(subjects, columns=["Subject"])
df

Subject
0   Computer Programming
1        Data Structures
2                    OOP
3  Programming Paradigms

#### 4. Citind dataset-ul dintr-un *fisier* (.csv, .json, .xlsx etc.)

In [ ]:
df = pd.read_csv("AWS_Honeypot.csv")
df.head()

datetime           host  ...  latitude longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

Cum putem afla informatii despre dataframe-ul creat?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Subject  4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes


Acest apel de **df.info()** ne va da mai multe detalii precum coloanele ce le contine dataframe-ul creat de noi, tipurile datelor stocate pe acele coloane, numarul de valori ce nu sunt
nule pe acele coloane, cat si memoria pe care o ocupa dataframe-ul nostru. \
De retinut: **memoria utilizata de dataframe** ce este intoarsa de **df.info()** este **memorie principala (RAM)** pentru ca *pandas* incarca dataframe-ul in RAM. Acest lucru poate fi costisitor si poate deveni un *bottleneck* in momentul in care lucram cu *Big Data*. \
Daca, totusi, dorim sa lucram cu date care sunt generate continuu, putem folosi Dask [1] sau PySpark [2].

## Valori Lipsa

In practica, putem intalni seturi de date cu valori lipsa. Un data scientist va deduce semnificatia acestora sau le va elimina in procesul de *data cleaning*.

NumPy foloseste ***np.nan*** pentru a indica valori lipsa. NaN (Not a Number) este o valoare de tip float in standardul IEEE, fapt ce permite utilizarea operatiilor matematice asupra structurilor care o contin. Toate operatiile efectuate asupra unor structuri ce contin NaN vor intoarce, la randul lor, NaN.

*Atentie!* np.nan este diferit de None, obiect de tip NoneType care nu accepta operatii matematice.

In [ ]:
a = None
b = np.nan
print(a is b)

In [ ]:
floats = np.array([2, np.nan, -1.3])
print(np.sum(floats))

Pentru a verifica daca o structura contine sau nu valori lipsa, putem folosi *isnull()*.

In [ ]:
series = pd.Series(["Jack", np.nan, "Frank", None])
series.isnull()

In momentul in care lucram cu valori lipsa trebuie sa avem o atentie sporita atunci cand este nevoie sa aplicam asupra lor functii statistice si de agregare din NumPy.

Cel mai bun exemplu in acest sens este reprezentat de utilizarea functiilor precum np.average, np.mean, np.std. Daca aceste functii sunt aplicate pe un set de date care contine valori lipsa, rezultatul intors de ele va fi np.nan.

In [ ]:
np.average(floats)

nan

In [ ]:
np.mean(floats)

nan

Pentru a putea aplica functiile statistice si de agregare pe care le dorim numai asupra datelor relevante au aparut functiile corespondente - np.nanmean, np.nanstd. Aceste functii sunt construite in asa mod incat sa nu ia in considerare valorile de tip np.nan in momentul calculului.

In [ ]:
np.nanmean(floats)

0.35

In [ ]:
np.nanstd(floats)

1.65

### **Demo DataFrames**

Vom folosi setul de date *AWS_Honeypot.csv*.

#### *Ce este un Honeypot?*

Un *honeypot* reprezinta un sistem atasat la retea drept "momeala" pentru atacurile cibernetice. Fiind intentionat vulnerabil, acesta face posibila detectarea, devierea si investigarea incercarilor neautorizate de a accesa informatii interne din sistemul principal. Masinile virtuale sunt deseori utilizate pentru a hosta honeypot-uri (pot fi usor restaurate daca sunt compromise).
* *honeynet*: doua sau mai multe honeypot-uri
* *honey farm*: colectie centralizata de honeypot-uri si instrumente de analiza a datelor

![picture](https://drive.google.com/uc?export=view&id=1plXhhQF78u1NYy62JD49EK3vKwJOpv-O)

In acest demo vom simula un analizor de honeypot.



In [ ]:
import pandas as pd
import numpy as np

# tinem datasetul honeypot intr-un dataframe
honeypot = pd.read_csv("AWS_Honeypot.csv")
honeypot.head()

datetime           host  ...  latitude longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

#### Cum accesam datele dintr-un dataframe?

##### 1. ***iloc***

In mod similar cu Series, atributul iloc[n] va intoarce a n-a inregistrare din tabel.

Verificam data ultimei inregistrari din honeypot, inainte de restaurare:

In [ ]:
# va returna ultima intrare/rand din dataframe
honeypot.iloc[-1]

datetime           3/8/13 7:36
host         groucho-singapore
src                 3342555165
proto                     ICMP
type                         0
spt                        NaN
dpt                        NaN
srcstr            199.59.88.29
country          United States
locale                Michigan
latitude               42.5065
longitude             -83.3491
Name: 443, dtype: object

In [ ]:
# va returna primul element din ultima intrare din dataframe ce corespunde
# "datetime"-ului
honeypot.iloc[-1, 0]

'3/8/13 7:36'

##### 2. ***loc***

Pentru a extrage datele despre toate atacurile cu sursa in Romania, putem indexa dupa tara, apoi selecta dupa label folosind atributul loc:

In [ ]:
honeypot.reset_index(inplace=True)
honeypot.set_index("country", inplace=True)
honeypot.loc["Romania"]

index     datetime  ... latitude  longitude
country                      ...                    
Romania      8  3/8/13 1:19  ...    45.15    26.8333
Romania      9  3/8/13 1:20  ...    45.15    26.8333
Romania    297  3/8/13 5:28  ...    44.20    27.3333
Romania    298  3/8/13 5:28  ...    44.20    27.3333

[4 rows x 12 columns]

In [ ]:
# pentru a gasi "locale" pentru Romania
honeypot.loc["Romania", "locale"].drop_duplicates()

country
Romania       Judetul Buzau
Romania    Judetul Calarasi
Name: locale, dtype: object

Putem folosi atributul loc pentru preluarea datelor dupa orice label nominal:

In [ ]:
# folosind .loc si masca booleana putem gasi toate atacurile din Germania
honeypot = pd.read_csv("AWS_Honeypot.csv")
honeypot.loc[honeypot["country"]=="Germany"]

datetime           host  ...  latitude longitude
4    3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266
90   3/8/13 2:34  groucho-tokyo  ...   49.5372    8.3550
121  3/8/13 2:35  groucho-tokyo  ...   51.0000    9.0000
122  3/8/13 2:35  groucho-tokyo  ...   51.0000    9.0000

[4 rows x 12 columns]

##### 3. Folosind *numele unei coloane*

Extragem toate tarile din care s-au incercat atacurile catre acest honeypot:

In [ ]:
attacker_countries = honeypot["country"].drop_duplicates(keep="first")
attacker_countries.reset_index(drop=True)

0                Netherlands
1                     Poland
2                      China
3                    Germany
4                    Romania
5             United Kingdom
6              United States
7               South Africa
8                Philippines
9                     Taiwan
10               South Korea
11                    Brazil
12                 Hong Kong
13                       NaN
14                     India
15                    Latvia
16                    Canada
17    Bosnia and Herzegovina
18                 Indonesia
19                    France
20      United Arab Emirates
21                  Malaysia
22                  Thailand
23                   Austria
24                   Vietnam
25                 Australia
26                     Japan
27                 Sri Lanka
28                    Israel
Name: country, dtype: object

De ce necesar apelul de **drop_duplicates()** in procesul de *curatare* al datelor? \
Deoarece in momentul in care antrenam algoritmi de *Machine Learning* pe seturi de date care contin duplicate, acestea pot favoriza un anumit exemplu sau anumite *features* ce sunt extrase din acel exemplu in detrimentul altora, din cauza ponderii pe care o au. De asemenea, poate pastrarea duplicatelor face mai usor *data leakage*-ul despre care vom vorbi in Laboratorul 10.  

##### 4. Prin *slicing* si/sau *subsetting* (lista de indecsi, coloane)

In [ ]:
honeypot.loc[:100, ["datetime", "spt", "dpt"]]

datetime     spt     dpt
0    3/8/13 1:11  2065.0    23.0
1    3/8/13 1:12  4667.0    23.0
2    3/8/13 1:14     NaN     NaN
3    3/8/13 1:14     NaN     NaN
4    3/8/13 1:16  3422.0    23.0
..           ...     ...     ...
96   3/8/13 2:33  5093.0  5066.0
97   3/8/13 2:33  5093.0  5070.0
98   3/8/13 2:33  5093.0  5068.0
99   3/8/13 2:33  5093.0  5064.0
100  3/8/13 2:33  5093.0  5069.0

[101 rows x 3 columns]

#### Cum redenumim titlurile coloanelor?

##### 1. ***df.rename***

df.rename(columns={old:new, ...})

In [ ]:
honeypot.rename(columns={"src": "bandwidth", "srcstr": "ip"}, inplace=True)
honeypot.head()

datetime           host  ...  latitude longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

##### 2. ***mapper***

Este folosit tot prin df.rename().

De aceasta data, este data ca parametru o functie (mapper) care indica modificarile asupra titlurilor coloanelor (axis=1) sau indecsilor (axis=0).

In [ ]:
def port_foo(column):
  if (column == "spt"):
    return "Src Port"
  if (column == "dpt"):
    return "Dst Port"
  return column

honeypot.rename(mapper=port_foo, axis=1, inplace=True)
honeypot.head()

datetime           host  ...  latitude longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

##### 3. ***df.columns***

df.columns = ["col0_new", "col1_new", ....]

Se precizeaza noile valori pentru toate coloanele, in ordine.

In [ ]:
honeypot.columns = ["DateTime", "Host", "Bandwidth", "Protocol",\
                    "Type", "SrcPort", "DstPort", "IP", "Country",\
                    "Locale", "Latitude", "Longitude"]
honeypot.head()

DateTime           Host  ...  Latitude Longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

#### Cum scriem query-uri folosind Boolean Masking?

Vrem sa gasim date despre atacurile din China interceptate incepand cu ora 5:00 (toate inregistrarile din honeypot-ul dat au loc in aceeasi zi) .

*Pandas are functionalitati speciale pentru lucrul cu date si ore. De exemplu, pd.to_datetime() converteste orice format orar la unul standard.*

In [ ]:
import datetime
honeypot = pd.read_csv("AWS_Honeypot.csv")
honeypot["datetime"] = pd.to_datetime(honeypot["datetime"])
honeypot.head()

/tmp/ipykernel_8927/4148416983.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  honeypot["datetime"] = pd.to_datetime(honeypot["datetime"])


datetime           host         src proto  type     spt   dpt  \
0 2013-03-08 01:11:00  groucho-tokyo  1398184219   TCP   NaN  2065.0  23.0   
1 2013-03-08 01:12:00  groucho-tokyo  1393252776   TCP   NaN  4667.0  23.0   
2 2013-03-08 01:14:00     groucho-sa  3662430566  ICMP   8.0     NaN   NaN   
3 2013-03-08 01:14:00     groucho-sa  3662430566  ICMP   8.0     NaN   NaN   
4 2013-03-08 01:16:00  groucho-tokyo   411470328   TCP   NaN  3422.0  23.0   

           srcstr      country              locale  latitude  longitude  
0    83.86.153.27  Netherlands       South Holland   52.1763     4.5282  
1    83.11.89.168       Poland  Kujawsko-Pomorskie   52.5931    19.0894  
2   218.76.65.102        China               Hunan   28.1792   113.1136  
3   218.76.65.102        China               Hunan   28.1792   113.1136  
4  24.134.137.248      Germany        Lower Saxony   53.5568     8.1266

Putem crea doua masti - una pentru fiecare conditie - si sa accesam dataframe-ul cu ajutorul lor.

*Atentie!*
* operatorii logici sunt bitwise-like (fata de Python, unde avem "and", "or")
* locul parantezelor conteaza

Avem doua posibilitati:

##### 1. *df[mask]*

In [ ]:
start_time = "2013-03-08 05:00:00"

honeypot[(honeypot["datetime"] >= start_time) & (honeypot["country"] == "China")].reset_index(drop=True)

datetime               host         src proto  type      spt  \
0  2013-03-08 05:01:00      groucho-tokyo  3658020275   TCP   NaN   6000.0   
1  2013-03-08 05:03:00  groucho-singapore  3729578419   TCP   NaN   6000.0   
2  2013-03-08 05:11:00  groucho-singapore  1033070424   TCP   NaN   6000.0   
3  2013-03-08 05:14:00      groucho-tokyo   710975177   TCP   NaN   6000.0   
4  2013-03-08 05:30:00      groucho-tokyo  1991904499   TCP   NaN   6000.0   
..                 ...                ...         ...   ...   ...      ...   
66 2013-03-08 07:30:00     groucho-oregon   710974991   TCP   NaN   7827.0   
67 2013-03-08 07:31:00         groucho-eu  3722483078   TCP   NaN  58313.0   
68 2013-03-08 07:31:00         groucho-eu  3722483078   TCP   NaN  58313.0   
69 2013-03-08 07:31:00         groucho-eu  3722483078   TCP   NaN  58313.0   
70 2013-03-08 07:33:00     groucho-oregon  1995749293   TCP   NaN   6000.0   

        dpt           srcstr country              locale  latitude  longitude  
0    1433.0    218.8.245.179   China  Heilongjiang Sheng   45.7500   126.6500  
1   65500.0   222.76.217.179   China              Fujian   24.4798   118.0819  
2    1433.0    61.147.103.88   China       Jiangsu Sheng   32.0617   118.7778  
3    3306.0    42.96.158.201   China         Beijing Shi   39.9289   116.3883  
4    1433.0   118.186.12.243   China         Beijing Shi   39.9289   116.3883  
..      ...              ...     ...                 ...       ...        ...  
66   1433.0     42.96.158.15   China         Beijing Shi   39.9289   116.3883  
67   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
68   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
69   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
70   1433.0  118.244.183.173   China         Beijing Shi   39.9289   116.3883  

[71 rows x 12 columns]

##### 2. *df.where(mask)*

Mai jos avem un exemplu de *Pandas Chaining*. Mai multe metode sunt aplicate pe rand aceluiasi obiect prin inlantuire, crescand lizibilitatea codului. In cazul nostru, mai intai aplicam o masca pentru filtrare, apoi eliminam liniile care au cel putin doua valori NaN.

In [ ]:
honeypot.where((honeypot["datetime"] >= start_time) & (honeypot["country"] == "China")).dropna(thresh=2)


datetime               host           src proto  type      spt  \
289 2013-03-08 05:01:00      groucho-tokyo  3.658020e+09   TCP   NaN   6000.0   
291 2013-03-08 05:03:00  groucho-singapore  3.729578e+09   TCP   NaN   6000.0   
293 2013-03-08 05:11:00  groucho-singapore  1.033070e+09   TCP   NaN   6000.0   
294 2013-03-08 05:14:00      groucho-tokyo  7.109752e+08   TCP   NaN   6000.0   
301 2013-03-08 05:30:00      groucho-tokyo  1.991904e+09   TCP   NaN   6000.0   
..                  ...                ...           ...   ...   ...      ...   
432 2013-03-08 07:30:00     groucho-oregon  7.109750e+08   TCP   NaN   7827.0   
433 2013-03-08 07:31:00         groucho-eu  3.722483e+09   TCP   NaN  58313.0   
434 2013-03-08 07:31:00         groucho-eu  3.722483e+09   TCP   NaN  58313.0   
435 2013-03-08 07:31:00         groucho-eu  3.722483e+09   TCP   NaN  58313.0   
436 2013-03-08 07:33:00     groucho-oregon  1.995749e+09   TCP   NaN   6000.0   

         dpt           srcstr country              locale  latitude  longitude  
289   1433.0    218.8.245.179   China  Heilongjiang Sheng   45.7500   126.6500  
291  65500.0   222.76.217.179   China              Fujian   24.4798   118.0819  
293   1433.0    61.147.103.88   China       Jiangsu Sheng   32.0617   118.7778  
294   3306.0    42.96.158.201   China         Beijing Shi   39.9289   116.3883  
301   1433.0   118.186.12.243   China         Beijing Shi   39.9289   116.3883  
..       ...              ...     ...                 ...       ...        ...  
432   1433.0     42.96.158.15   China         Beijing Shi   39.9289   116.3883  
433   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
434   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
435   3389.0  221.224.149.134   China       Jiangsu Sheng   32.0617   118.7778  
436   1433.0  118.244.183.173   China         Beijing Shi   39.9289   116.3883  

[71 rows x 12 columns]

#### Cum manipulam un DataFrame folosind functionale?

Acest honey farm colecteaza valorile bandwidth-ului unui atac in bps (biti per secunda), ceea ce le face greu de urmarit.

Vom crea o functie care va converti bandwidth-ul la Gbps (gigabiti per secunda) si o vom aplica pe datele din dataframe folosind *apply()*.

In [ ]:
honeypot = pd.read_csv("AWS_Honeypot.csv")

def convert_to_gbps(bandwidth):
  return round((float) (bandwidth / (10 ** 9)), 2)

honeypot["src"] = honeypot["src"].apply(lambda x: convert_to_gbps(x))
honeypot.head()

NameError: name 'pd' is not defined

#### Optional: Good to know: Cum intelegem datele la nivel de grup? *(groupby)*

Dorim sa interpretam datele in functie de protocolul folosit in atac:

In [ ]:
for group, frame in honeypot.groupby("proto"):
  print(str(group) + ": " + str(len(frame)) + " records")

ICMP: 56 records
TCP: 309 records
UDP: 79 records


##### **GroupBy** este un proces ce implica cel putin unul din pasii *split-apply-combine*:

*   *split*: datele se impart in grupuri dupa un criteriu
*   *apply*: se aplica o functie pe fiecare grup
*   *combine*: rezultatele sunt agregate intr-o structura

La pasul apply, putem folosi groupby() impreuna cu una din functiile:

*Aggregate*

Pasam un dictionar avand numele coloanelor de interpretat drept chei si functiile necesare interpretarii drept valori.

Analizam in continuare grupurile, calculand bandwidth-ul mediu si latitudinea minima pentru fiecare:

In [ ]:
honeypot.groupby("proto").agg({"src": np.nanmean, "latitude": np.min})

src  latitude
proto                    
ICMP   2.705536  -33.8615
TCP    2.108964  -33.8615
UDP    2.856203   13.7567

*Filter*

Pasam o functie care se aplica pe fiecare grup si intoarce True sau False, in functie de rezultatul grupului la filtru.

Vrem sa gasim informatii doar despre atacurile din grupurile care au media bandwidth-ului mai mare de 2.5 Gbps:

In [ ]:
# gasim informatii doar despre atacurile din grupurile care au media
# bandwidth-ului mai mare de 2.5 Gbps
bw = honeypot.groupby("proto").filter(lambda df: np.nanmean(df["src"]) > 2.5)
bw.reset_index(inplace=True)
bw.drop(columns="index")


datetime               host   src  ...          locale  latitude  longitude
0    3/8/13 1:14         groucho-sa  3.66  ...           Hunan   28.1792   113.1136
1    3/8/13 1:14         groucho-sa  3.66  ...           Hunan   28.1792   113.1136
2    3/8/13 1:21         groucho-eu  2.01  ...  Shandong Sheng   36.6683   116.9972
3    3/8/13 1:21         groucho-eu  2.01  ...  Shandong Sheng   36.6683   116.9972
4    3/8/13 1:22         groucho-sa  3.43  ...        Colorado   39.7525  -104.9995
..           ...                ...   ...  ...             ...       ...        ...
130  3/8/13 7:35    groucho-us-east  1.92  ...        Tokyo-to   35.6850   139.7514
131  3/8/13 7:35    groucho-us-east  1.92  ...        Tokyo-to   35.6850   139.7514
132  3/8/13 7:35    groucho-us-east  1.92  ...        Tokyo-to   35.6850   139.7514
133  3/8/13 7:36    groucho-us-east  1.92  ...        Tokyo-to   35.6850   139.7514
134  3/8/13 7:36  groucho-singapore  3.34  ...        Michigan   42.5065   -83.3491

[135 rows x 12 columns]

*Apply*

Pasam o functie care se va aplica pe fiecare grup, oferindu-ne posibilitatea de a pastra rezultatele obtinute in cadrul aceluiasi dataframe.

Intentionam sa grupam atacurile dupa protocolul folosit si sa aflam care este deviatia standard a fiecarui atac fata de media grupului din care face parte.

In [ ]:
df = honeypot[['src', 'proto']]

def compute_std_dev(group):
  avg = np.nanmean(group['src'])
  group['avg'] = avg
  group['std_dev'] = np.abs(avg - group['src'])
  return group

df.groupby('proto').apply(compute_std_dev)

src proto       avg   std_dev
0    1.40   TCP  2.108964  0.708964
1    1.39   TCP  2.108964  0.718964
2    3.66  ICMP  2.705536  0.954464
3    3.66  ICMP  2.705536  0.954464
4    0.41   TCP  2.108964  1.698964
..    ...   ...       ...       ...
439  1.92   UDP  2.856203  0.936203
440  1.92   UDP  2.856203  0.936203
441  1.92   UDP  2.856203  0.936203
442  1.92   UDP  2.856203  0.936203
443  3.34  ICMP  2.705536  0.634464

[444 rows x 4 columns]

#### Cum analizam datele din mai multe surse? *(merging dataframes)*

Pandas vine la dispozitie cu instrumente in acest scop, precum *merge()* (similar join-ului din SQL) si *concat()*.

In [ ]:
first = pd.read_csv("AWS_Honeypot.csv")
first = first.head(5)
print(first.shape)
first

(5, 12)


datetime           host  ...  latitude longitude
0  3/8/13 1:11  groucho-tokyo  ...   52.1763    4.5282
1  3/8/13 1:12  groucho-tokyo  ...   52.5931   19.0894
2  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
3  3/8/13 1:14     groucho-sa  ...   28.1792  113.1136
4  3/8/13 1:16  groucho-tokyo  ...   53.5568    8.1266

[5 rows x 12 columns]

In [ ]:
pip install pandas-ods-reader

     |████████████████████████████████| 6.3 MB 36.7 MB/s 
     |████████████████████████████████| 125 kB 68.4 MB/s 
  Created wheel for ezodf: filename=ezodf-0.3.2-py2.py3-none-any.whl size=49002 sha256=10974f6b33f20201329e6ca8479357a61cbaf960d184d91d4a44a1e9c7078bad
  Stored in directory: /root/.cache/pip/wheels/8f/60/52/bffa36b97e0136aa62d54948d56e8770b96a5da7f9c65fdd85
Successfully built ezodf
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6


In [ ]:
pip install odfpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.0/717.0 kB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=160672 sha256=2d3968399f2fbe950f704f147bd964cad4e871e78ee21fba1a5cdc2f6ab951db
  Stored in directory: /root/.cache/pip/wheels/c8/2e/95/90d94fe33903786937f3b8c33dd88807f792359c6424b40469
Successfully built odfpy


In [ ]:
#loc = pd.read_ods("AWS_Honeypot_location.ods")
loc = pd.read_excel("AWS_Honeypot_location.ods", engine="odf")
loc = loc.head(10)
print(loc.shape)
loc

(10, 8)


datetime            host  ... latitude longitude
0  3/8/13 1:11   groucho-tokyo  ...  52.1763    4.5282
1  3/8/13 1:12   groucho-tokyo  ...  52.5931   19.0894
2  3/8/13 1:14      groucho-sa  ...  28.1792  113.1136
3  3/8/13 1:14      groucho-sa  ...  28.1792  113.1136
4  3/8/13 1:16   groucho-tokyo  ...  53.5568    8.1266
5  3/8/13 1:16  groucho-oregon  ...  28.5500  115.9333
6  3/8/13 1:17   groucho-tokyo  ...  28.1792  113.1136
7  3/8/13 1:18   groucho-tokyo  ...  32.0617  118.7778
8  3/8/13 1:19   groucho-tokyo  ...  45.1500   26.8333
9  3/8/13 1:20   groucho-tokyo  ...  45.1500   26.8333

[10 rows x 8 columns]

##### *Inner Merge*

Join-ul se va face dupa coloanele comune.
Este tipul implicit de merge.

In [ ]:
inner = pd.merge(first, loc)
print(inner.shape)
inner

NameError: ignored

Putem preciza coloanele dupa care vrem sa facem merge folosind *on*.

Coloanele care se regasesc in ambele dataframe-uri, dar nu sunt folosite drept valori pentru *on*, se vor interpreta individual si, deci, vor aparea impreuna in noul dataframe. Acestea se vor diferentia prin indicele atasat la final (*_x*, *_y*).

In [ ]:
inner = pd.merge(first, loc, on=["host", "srcstr"])
print(inner.shape)
inner

NameError: ignored

##### *Outer Merge*

Combina toate liniile din cele doua dataframe-uri, adaugand NaN acolo unde nu se gasesc valori corespunzatoare.

In [ ]:
outer = pd.merge(first, loc, how="outer")
print(outer.shape)
outer

(12, 15)


datetime            host           src  ...  cc  localeabbr  postalcode
0   3/8/13 1:11   groucho-tokyo  1.398184e+09  ...  NL          ZH         NaN
1   3/8/13 1:12   groucho-tokyo  1.393253e+09  ...  PL          KP         NaN
2   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
3   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
4   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
5   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
6   3/8/13 1:16   groucho-tokyo  4.114703e+08  ...  DE          NI     26386.0
7   3/8/13 1:16  groucho-oregon           NaN  ...  CN          36         NaN
8   3/8/13 1:17   groucho-tokyo           NaN  ...  CN          43         NaN
9   3/8/13 1:18   groucho-tokyo           NaN  ...  CN          32         NaN
10  3/8/13 1:19   groucho-tokyo           NaN  ...  RO          BZ         NaN
11  3/8/13 1:20   groucho-tokyo           NaN  ...  RO          BZ         NaN

[12 rows x 15 columns]

##### *Left (Outer) Merge*

Pastreaza toate liniile din dataframe-ul stang. Va adauga NaN acolo unde nu exista valori corespunzatoare pentru variabila *on* in dataframe-ul drept.

In [ ]:
left = pd.merge(first, loc, how="left", on=["datetime", "host", "latitude", "longitude"])
print(left.shape)
left

(7, 16)


datetime           host         src  ...  cc  localeabbr  postalcode
0  3/8/13 1:11  groucho-tokyo  1398184219  ...  NL          ZH         NaN
1  3/8/13 1:12  groucho-tokyo  1393252776  ...  PL          KP         NaN
2  3/8/13 1:14     groucho-sa  3662430566  ...  CN          43         NaN
3  3/8/13 1:14     groucho-sa  3662430566  ...  CN          43         NaN
4  3/8/13 1:14     groucho-sa  3662430566  ...  CN          43         NaN
5  3/8/13 1:14     groucho-sa  3662430566  ...  CN          43         NaN
6  3/8/13 1:16  groucho-tokyo   411470328  ...  DE          NI     26386.0

[7 rows x 16 columns]

##### *Right (Outer) Merge*

Pastreaza toate liniile din dataframe-ul drept. Va adauga NaN acolo unde nu exista valori corespunzatoare pentru variabila *on* in dataframe-ul stang.

In [ ]:
right = pd.merge(first, loc, how="right", on=["datetime", "host", "latitude", "longitude"])
print(right.shape)
right

(12, 16)


datetime            host           src  ...  cc  localeabbr  postalcode
0   3/8/13 1:11   groucho-tokyo  1.398184e+09  ...  NL          ZH         NaN
1   3/8/13 1:12   groucho-tokyo  1.393253e+09  ...  PL          KP         NaN
2   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
3   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
4   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
5   3/8/13 1:14      groucho-sa  3.662431e+09  ...  CN          43         NaN
6   3/8/13 1:16   groucho-tokyo  4.114703e+08  ...  DE          NI     26386.0
7   3/8/13 1:16  groucho-oregon           NaN  ...  CN          36         NaN
8   3/8/13 1:17   groucho-tokyo           NaN  ...  CN          43         NaN
9   3/8/13 1:18   groucho-tokyo           NaN  ...  CN          32         NaN
10  3/8/13 1:19   groucho-tokyo           NaN  ...  RO          BZ         NaN
11  3/8/13 1:20   groucho-tokyo           NaN  ...  RO          BZ         NaN

[12 rows x 16 columns]

Primim un nou set de date din honeypot.

##### *Concat*

In [ ]:
from pandas_ods_reader import read_ods

second = read_ods("AWS_Honeypot_2.ods")
second = second.head(5)
print(second.shape)
second

(5, 15)


datetime               host  ...  latitude longitude
0  3/8/13 7:47  groucho-singapore  ...   39.9289  116.3883
1  3/8/13 7:50      groucho-tokyo  ...   39.7525 -104.9995
2  3/8/13 7:53      groucho-tokyo  ...   22.2833  114.1500
3  3/8/13 7:53      groucho-tokyo  ...   22.2833  114.1500
4  3/8/13 7:53  groucho-singapore  ...   30.2936  120.1614

[5 rows x 15 columns]

Folosind parametrul axis, putem specifica daca dorim concatenarea dataframe-urilor pe verticala, de-a lungul liniilor (axis=0) sau pe orizontala, de-a lungul coloanelor (axis=1).

In [ ]:
all = pd.concat([first, second], axis=0)
print(all.shape)
all

(10, 15)


datetime               host           src  ...   cc  localeabbr  postalcode
0  3/8/13 1:11      groucho-tokyo  1.398184e+09  ...  NaN         NaN         NaN
1  3/8/13 1:12      groucho-tokyo  1.393253e+09  ...  NaN         NaN         NaN
2  3/8/13 1:14         groucho-sa  3.662431e+09  ...  NaN         NaN         NaN
3  3/8/13 1:14         groucho-sa  3.662431e+09  ...  NaN         NaN         NaN
4  3/8/13 1:16      groucho-tokyo  4.114703e+08  ...  NaN         NaN         NaN
0  3/8/13 7:47  groucho-singapore  7.109706e+08  ...   CN          11         NaN
1  3/8/13 7:50      groucho-tokyo  1.279864e+09  ...   US          CO     80202.0
2  3/8/13 7:53      groucho-tokyo  2.011989e+09  ...   HK        None         NaN
3  3/8/13 7:53      groucho-tokyo  2.011989e+09  ...   HK        None         NaN
4  3/8/13 7:53  groucho-singapore  2.061592e+09  ...   CN          33         NaN

[10 rows x 15 columns]

In [ ]:
all = pd.concat([first, loc], axis=1)
# ruleaza celula, apoi decomenteaza linia urmatoare
# all = all.loc[:,~all.columns.duplicated()]
print(all.shape)
all

(10, 20)


datetime           host           src  ... postalcode  latitude  longitude
0  3/8/13 1:11  groucho-tokyo  1.398184e+09  ...        NaN   52.1763     4.5282
1  3/8/13 1:12  groucho-tokyo  1.393253e+09  ...        NaN   52.5931    19.0894
2  3/8/13 1:14     groucho-sa  3.662431e+09  ...        NaN   28.1792   113.1136
3  3/8/13 1:14     groucho-sa  3.662431e+09  ...        NaN   28.1792   113.1136
4  3/8/13 1:16  groucho-tokyo  4.114703e+08  ...    26386.0   53.5568     8.1266
5          NaN            NaN           NaN  ...        NaN   28.5500   115.9333
6          NaN            NaN           NaN  ...        NaN   28.1792   113.1136
7          NaN            NaN           NaN  ...        NaN   32.0617   118.7778
8          NaN            NaN           NaN  ...        NaN   45.1500    26.8333
9          NaN            NaN           NaN  ...        NaN   45.1500    26.8333

[10 rows x 20 columns]

# Exercitii Laborator

In exercitiile propuse spre rezolvare, vom folosi urmatoarele dataset-uri:
*   *movies.csv*
      * contine date despre filmele din top 100 IMDB (precum titlul, anul aparitiei, rating, gen)
*   *academy_awards.xlsx*
* *bafta.xlsx*
* *golden_globes.xlsx*
  
  * contin informatii despre nominalizari si premii castigate la 3 festivaluri de catre filmele din top 100 IMDB
  * cele 6 categorii luate in considerare (ex. best film, best actor) au aceeasi denumire in toate cele 3 dataset-uri
  * in dreptul unei categorii, un film poate avea una din urmatoarele valori:
    * *1*, daca filmul a castigat acel premiu
    * *2*, daca filmul a fost nominalizat pentru acel premiu, dar nu a castigat
    * *nicio valoare*, daca filmul nu a fost nici macar nominalizat pentru acel premiu (se poate interpreta ca nan)


In [3]:
import pandas as pd
import numpy as np

# top 100 IMDB movies
movies = pd.read_csv("movies.csv")
movies.head()

imdb_title_id            original_title  year                 genre  \
0     tt0111161  The Shawshank Redemption  1994                 Drama   
1     tt0068646             The Godfather  1972          Crime, Drama   
2     tt0071562    The Godfather: Part II  1974          Crime, Drama   
3     tt0468569           The Dark Knight  2008  Action, Crime, Drama   
4     tt0050083              12 Angry Men  1957          Crime, Drama   

   duration              director                             writer  \
0       142        Frank Darabont       Stephen King, Frank Darabont   
1       175  Francis Ford Coppola   Mario Puzo, Francis Ford Coppola   
2       202  Francis Ford Coppola   Francis Ford Coppola, Mario Puzo   
3       152     Christopher Nolan  Jonathan Nolan, Christopher Nolan   
4        96          Sidney Lumet       Reginald Rose, Reginald Rose   

          production_company  \
0  Castle Rock Entertainment   
1         Paramount Pictures   
2         Paramount Pictures   
3               Warner Bros.   
4     Orion-Nova Productions   

                                              actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                         description  avg_vote    votes  
0  Two imprisoned men bond over a number of years...       9.3  2278845  
1  The aging patriarch of an organized crime dyna...       9.2  1572674  
2  The early life and career of Vito Corleone in ...       9.0  1098714  
3  When the menace known as the Joker wreaks havo...       9.0  2241615  
4  A jury holdout attempts to prevent a miscarria...       8.9   668473

In [8]:
# awards
academy_awards = pd.read_excel("academy_awards.xlsx")
bafta = pd.read_excel("bafta.xlsx")
golden_globes = pd.read_excel("golden_globes.xlsx")

academy_awards.head()

id            original_title        Festival  Year  Best 1 (picture)  \
0   1  The Shawshank Redemption  Academy Awards  1995               2.0   
1   2             The Godfather  Academy Awards  1973               1.0   
2   3    The Godfather: Part II  Academy Awards  1975               1.0   
3   4           The Dark Knight  Academy Awards  2009               NaN   
4   5              12 Angry Men  Academy Awards  1958               2.0   

   Best 2 (actor)  Best 3 (actress)  Best 4 (director)   \
0             2.0               NaN                 NaN   
1             1.0               NaN                 2.0   
2             2.0               NaN                 1.0   
3             NaN               NaN                 NaN   
4             NaN               NaN                 2.0   

   Best 5 (supporting actor)  Best 6 (supporting actress)  
0                        NaN                          NaN  
1                        2.0                          NaN  
2                        1.0                          NaN  
3                        1.0                          NaN  
4                        NaN                          NaN

### 1. In dataframe-urile corespunzatoare celor trei festivaluri, redenumiti astfel:

  * Numele coloanelor corespunzatoare categoriilor de premii:

        "Best 1 (picture)": "Best Picture"
        "Best 2 (actor)": "Best Actor"
        "Best 3 (actress)": "Best Actress"
        "Best 4 (director)": "Best Director"
        "Best 5 (supporting actor)": "Best Supporting Actor"
        "Best 6 (supporting actress)": "Best Supporting Actress"

  * Numele unor titluri de film cu traducerile lor in engleza:
  
        "Il buono, il brutto, il cattivo" : "The Good, the Bad and the Ugly"
        "Dag II" : "The Mountain II"
        "Schichinin no samurai" : "Seven Samurai"
        "Sen to Chihiro no kamikakushi" : "Spirited Away"
        "Gisaengchung" : "Parasite"
        "C'era una volta il West" : "Once Upon A Time  in the West"
        "Hotaru no haka" : "Grave of the Fireflies"
        "Mononoke-hime" : "Princess Mononoke"
        "Oldeuboi" : "Oldboy"
        "Das Leben ser Anderen" : "The Lives of Others"
        "Kimi no na wa." : "Your Name."
        "Capharnaüm" : "Capernaum"
        "Ladri di biciclette" : "Bycicle Thieves"
        "Per qualche dollaro in più" : "For a Few Dollars More"


In [10]:
column_mapping = {"Best 1 (picture)": "Best Picture",
        "Best 2 (actor)": "Best Actor",
        "Best 3 (actress)": "Best Actress",
        "Best 4 (director) ": "Best Director",
        "Best 5 (supporting actor)": "Best Supporting Actor",
        "Best 6 (supporting actress)": "Best Supporting Actress"}
title_mapping = {
    "Il buono, il brutto, il cattivo" : "The Good, the Bad and the Ugly",
        "Dag II" : "The Mountain II",
        "Schichinin no samurai" : "Seven Samurai",
        "Sen to Chihiro no kamikakushi" : "Spirited Away",
        "Gisaengchung" : "Parasite",
        "C'era una volta il West" : "Once Upon A Time  in the West",
        "Hotaru no haka" : "Grave of the Fireflies",
        "Mononoke-hime" : "Princess Mononoke",
        "Oldeuboi" : "Oldboy",
        "Das Leben ser Anderen" : "The Lives of Others",
        "Kimi no na wa." : "Your Name.",
        "Capharnaüm" : "Capernaum",
        "Ladri di biciclette" : "Bycicle Thieves",
        "Per qualche dollaro in più" : "For a Few Dollars More"
}
academy_awards = academy_awards.rename(columns=column_mapping)
bafta = bafta.rename(columns=column_mapping)
golden_globes = golden_globes.rename(columns=column_mapping)
academy_awards.head()
movies = movies.replace(title_mapping)
# print(movies)
academy_awards.head()

id            original_title        Festival  Year  Best Picture  \
0   1  The Shawshank Redemption  Academy Awards  1995           2.0   
1   2             The Godfather  Academy Awards  1973           1.0   
2   3    The Godfather: Part II  Academy Awards  1975           1.0   
3   4           The Dark Knight  Academy Awards  2009           NaN   
4   5              12 Angry Men  Academy Awards  1958           2.0   

   Best Actor  Best Actress  Best Director  Best Supporting Actor  \
0         2.0           NaN            NaN                    NaN   
1         1.0           NaN            2.0                    2.0   
2         2.0           NaN            1.0                    1.0   
3         NaN           NaN            NaN                    1.0   
4         NaN           NaN            2.0                    NaN   

   Best Supporting Actress  
0                      NaN  
1                      NaN  
2                      NaN  
3                      NaN  
4                      NaN

### 2. Adaugati cate doua coloane noi fiecaruia dintre cele trei dataframe-uri de tip festival, astfel:


* o coloana numita "Winner", continand numarul total de premii castigate de un film
* o coloana numita "Nominee", continand numarul total de nominalizari ale unui film

  *Atentie!* In acest calcul, vom considera ca un premiu castigat implica si o nominalizare.

In [11]:
award_categories = ['Best Picture', 'Best Actor', 'Best Actress', 'Best Director', 'Best Supporting Actor', 'Best Supporting Actress']

def count_prizes(row):
    count = 0
    for category in award_categories:
        if row[category] == 1:
            count += 1 
    return count

def count_nominees(row):
    count = 0
    for category in award_categories:
        if row[category] == 2 or row[category] == 1:
            count += 1 
    return count

academy_awards['Winner'] = academy_awards.apply(count_prizes, axis=1)
academy_awards['Nominee'] = academy_awards.apply(count_nominees, axis=1)

bafta['Winner'] = bafta.apply(count_prizes, axis=1)
bafta['Nominee'] = bafta.apply(count_nominees, axis=1)

golden_globes['Winner'] = golden_globes.apply(count_prizes, axis=1)
golden_globes['Nominee'] = golden_globes.apply(count_nominees, axis=1)

academy_awards.head()

id            original_title        Festival  Year  Best Picture  \
0   1  The Shawshank Redemption  Academy Awards  1995           2.0   
1   2             The Godfather  Academy Awards  1973           1.0   
2   3    The Godfather: Part II  Academy Awards  1975           1.0   
3   4           The Dark Knight  Academy Awards  2009           NaN   
4   5              12 Angry Men  Academy Awards  1958           2.0   

   Best Actor  Best Actress  Best Director  Best Supporting Actor  \
0         2.0           NaN            NaN                    NaN   
1         1.0           NaN            2.0                    2.0   
2         2.0           NaN            1.0                    1.0   
3         NaN           NaN            NaN                    1.0   
4         NaN           NaN            2.0                    NaN   

   Best Supporting Actress  Winner  Nominee  
0                      NaN       0        2  
1                      NaN       2        4  
2                      NaN       3        4  
3                      NaN       1        1  
4                      NaN       0        2

Acum avem o evidenta generala a castigurilor si nominalizarilor.

* Eliminati coloanele corespunzatoare celor sase categorii din fiecare dataframe si pastrati doar valorile calculate anterior.

In [13]:
columns_to_remove = ['Best Picture', 'Best Actor', 'Best Actress', 'Best Director', 'Best Supporting Actor', 'Best Supporting Actress']
academy_awards = academy_awards.drop(columns=columns_to_remove)
bafta = bafta.drop(columns=columns_to_remove)
golden_globes = golden_globes.drop(columns=columns_to_remove)

academy_awards.head()

KeyError: "['Best Picture', 'Best Actor', 'Best Actress', 'Best Director', 'Best Supporting Actor', 'Best Supporting Actress'] not found in axis"

### 3. Extrageti din fiecare festival filmul care a castigat cele mai multe premii. Creati un nou dataframe care sa contina aceste trei filme.

In [14]:

academy_awards_most_prizes = academy_awards.nlargest(1, 'Winner', 'all').head(1)
bafta_most_prizes = bafta.nlargest(1, 'Winner', 'all').head(1)
golden_globes_most_prizes = golden_globes.nlargest(1, 'Winner', 'all').head(1)

best_movies = pd.concat([academy_awards_most_prizes, bafta_most_prizes, golden_globes_most_prizes])

best_movies.head()




id                   original_title        Festival  Year  Winner  Nominee
15  16  One Flew Over the Cuckoo's Nest  Academy Awards  1976       4        5
15  16  One Flew Over the Cuckoo's Nest           BAFTA  1977       5        5
15  16  One Flew Over the Cuckoo's Nest   Golden Globes  1976       4        4

### 4. Care este filmul cu cele mai multe nominalizari la toate cele 3 festivaluri?

*Hint: concat(), set_index().*

In [17]:
academy_awards['Nominee'] = academy_awards['Nominee'].fillna(0)
bafta['Nominee'] = bafta['Nominee'].fillna(0)
golden_globes['Nominee'] = golden_globes['Nominee'].fillna(0)

combined_nominations = academy_awards['Nominee'] + bafta['Nominee'] + golden_globes['Nominee']

most_nominated_movie = combined_nominations.idxmax()
most_nominations = combined_nominations.max()

print(f"The movie with the most nominations is: {academy_awards.loc[most_nominated_movie]['original_title']} with {most_nominations} nominations.")

The movie with the most nominations is: Pulp Fiction with 14 nominations.


### 5. Ce proportie din filmele din top 100 IMDB nu au fost nominalizate la nici macar un festival?

In [32]:
top_100_movies = movies.sort_values(by='avg_vote', ascending=False).head(100)

top_100_movie_titles = top_100_movies['original_title'].tolist()

# print(top_100_movie_titles)

def was_nominated(title):
    return combined_nominations[combined_nominations['original_title'] == title]['Nominee'].all() > 0

not_nominated_count = sum(1 for title in top_100_movie_titles if not was_nominated(title))

percentage_not_nominated = (not_nominated_count / len(top_100_movie_titles)) * 100

print(f"The percentage of top 100 movies not nominated is: {percentage_not_nominated}%")

KeyError: 'original_title'

### 6. Returnati filmele care: au o nota mai mare strict decat 8.5 pe IMDB, sunt regizate de unul dintre regizorii ["Quentin Tarantino", "David Fincher", "Stanley Kubrik", "Christopher Nolan"] si sunt mai recente de 1989.

*Hint: boolean mask.*

In [49]:
directors = ["Quentin Tarantino", "David Fincher", "Stanley Kubrik", "Christopher Nolan"]
condition_1 = movies['avg_vote'] > 8.5
condition_2 = movies['director'].isin(directors)
condition_3 = movies['year'] > 1989

mask = condition_1 & condition_2 & condition_3

filtered_movies = movies[mask]

filtered_movies.head(100)

imdb_title_id   original_title  year                      genre  duration  \
3      tt0468569  The Dark Knight  2008       Action, Crime, Drama       152   
6      tt0110912     Pulp Fiction  1994               Crime, Drama       154   
11     tt0137523       Fight Club  1999                      Drama       139   
12     tt1375666        Inception  2010  Action, Adventure, Sci-Fi       148   
24     tt0114369            Se7en  1995      Crime, Drama, Mystery       127   
30     tt0816692     Interstellar  2014   Adventure, Drama, Sci-Fi       169   

             director                             writer  \
3   Christopher Nolan  Jonathan Nolan, Christopher Nolan   
6   Quentin Tarantino     Quentin Tarantino, Roger Avary   
11      David Fincher          Chuck Palahniuk, Jim Uhls   
12  Christopher Nolan                  Christopher Nolan   
24      David Fincher                Andrew Kevin Walker   
30  Christopher Nolan  Jonathan Nolan, Christopher Nolan   

      production_company                                             actors  \
3           Warner Bros.  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
6                Miramax  Tim Roth, Amanda Plummer, Laura Lovelace, John...   
11     Fox 2000 Pictures  Edward Norton, Brad Pitt, Meat Loaf, Zach Gren...   
12          Warner Bros.  Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...   
24  Cecchi Gori Pictures  Morgan Freeman, Andrew Kevin Walker, Daniel Za...   
30    Paramount Pictures  Ellen Burstyn, Matthew McConaughey, Mackenzie ...   

                                          description  avg_vote    votes  
3   When the menace known as the Joker wreaks havo...       9.0  2241615  
6   The lives of two mob hitmen, a boxer, a gangst...       8.9  1780147  
11  An insomniac office worker and a devil-may-car...       8.8  1807440  
12  A thief who steals corporate secrets through t...       8.8  2002816  
24  Two detectives, a rookie and a veteran, hunt a...       8.6  1402015  
30  A team of explorers travel through a wormhole ...       8.6  1449256

### 7. Calculati deviatia standard a rating-ului fiecarui film fata de nota medie a filmelor din acelasi gen.



Rezultatul poate fi fie o noua coloana, fie un Series.

In [51]:
grouped_by_genre = movies.groupby('genre')

genre_avg_rating = grouped_by_genre['avg_vote'].mean()

movies['std_deviation'] = grouped_by_genre['avg_vote'].transform(lambda x: x.std())

movies['std_deviation'] = movies['avg_vote'] - movies['genre'].map(genre_avg_rating)

movies.head()

imdb_title_id            original_title  year                 genre  \
0     tt0111161  The Shawshank Redemption  1994                 Drama   
1     tt0068646             The Godfather  1972          Crime, Drama   
2     tt0071562    The Godfather: Part II  1974          Crime, Drama   
3     tt0468569           The Dark Knight  2008  Action, Crime, Drama   
4     tt0050083              12 Angry Men  1957          Crime, Drama   

   duration              director                             writer  \
0       142        Frank Darabont       Stephen King, Frank Darabont   
1       175  Francis Ford Coppola   Mario Puzo, Francis Ford Coppola   
2       202  Francis Ford Coppola   Francis Ford Coppola, Mario Puzo   
3       152     Christopher Nolan  Jonathan Nolan, Christopher Nolan   
4        96          Sidney Lumet       Reginald Rose, Reginald Rose   

          production_company  \
0  Castle Rock Entertainment   
1         Paramount Pictures   
2         Paramount Pictures   
3               Warner Bros.   
4     Orion-Nova Productions   

                                              actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                         description  avg_vote    votes  \
0  Two imprisoned men bond over a number of years...       9.3  2278845   
1  The aging patriarch of an organized crime dyna...       9.2  1572674   
2  The early life and career of Vito Corleone in ...       9.0  1098714   
3  When the menace known as the Joker wreaks havo...       9.0  2241615   
4  A jury holdout attempts to prevent a miscarria...       8.9   668473   

   std_deviation  
0           0.70  
1           0.50  
2           0.30  
3           0.25  
4           0.20

### 8. Filtrati dataframe-ul movies, astfel incat sa contina doar filmele cu media rating-ului genului mai mare decat 8.65.

In [54]:
filtered_movies_by_genre = movies[movies['genre'].map(genre_avg_rating) > 8.65]

filtered_movies_by_genre.head(100)

imdb_title_id               original_title  year                    genre  \
1      tt0068646                The Godfather  1972             Crime, Drama   
2      tt0071562       The Godfather: Part II  1974             Crime, Drama   
3      tt0468569              The Dark Knight  2008     Action, Crime, Drama   
4      tt0050083                 12 Angry Men  1957             Crime, Drama   
6      tt0110912                 Pulp Fiction  1994             Crime, Drama   
9      tt0109830                 Forrest Gump  1994           Drama, Romance   
13     tt5813916              The Mountain II  2016       Action, Drama, War   
17     tt0099685                   Goodfellas  1990  Biography, Crime, Drama   
29     tt0317248               Cidade de Deus  2002             Crime, Drama   
42     tt0110413                         Léon  1994     Action, Crime, Drama   
62     tt0087843  Once Upon a Time in America  1984             Crime, Drama   
95     tt0075314                  Taxi Driver  1976             Crime, Drama   
98     tt0086250                     Scarface  1983             Crime, Drama   

    duration                        director  \
1        175            Francis Ford Coppola   
2        202            Francis Ford Coppola   
3        152               Christopher Nolan   
4         96                    Sidney Lumet   
6        154               Quentin Tarantino   
9        142                 Robert Zemeckis   
13       135                    Alper Caglar   
17       146                 Martin Scorsese   
29       130  Fernando Meirelles, Kátia Lund   
42       110                      Luc Besson   
62       229                    Sergio Leone   
95       114                 Martin Scorsese   
98       170                  Brian De Palma   

                                writer      production_company  \
1     Mario Puzo, Francis Ford Coppola      Paramount Pictures   
2     Francis Ford Coppola, Mario Puzo      Paramount Pictures   
3    Jonathan Nolan, Christopher Nolan            Warner Bros.   
4         Reginald Rose, Reginald Rose  Orion-Nova Productions   
6       Quentin Tarantino, Roger Avary                 Miramax   
9             Winston Groom, Eric Roth      Paramount Pictures   
13                        Alper Caglar                  3leven   
17  Nicholas Pileggi, Nicholas Pileggi            Warner Bros.   
29       Paulo Lins, Bráulio Mantovani               O2 Filmes   
42                          Luc Besson                 Gaumont   
62      Harry Grey, Leonardo Benvenuti        The Ladd Company   
95                       Paul Schrader       Columbia Pictures   
98                        Oliver Stone      Universal Pictures   

                                               actors  \
1   Marlon Brando, Al Pacino, James Caan, Richard ...   
2   Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3   Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4   Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   
6   Tim Roth, Amanda Plummer, Laura Lovelace, John...   
9   Tom Hanks, Rebecca Williams, Sally Field, Mich...   
13  Caglar Ertugrul, Ufuk Bayraktar, Ahu Türkpençe...   
17  Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...   
29  Alexandre Rodrigues, Leandro Firmino, Phellipe...   
42  Jean Reno, Gary Oldman, Natalie Portman, Danny...   
62  Robert De Niro, James Woods, Elizabeth McGover...   
95  Diahnne Abbott, Frank Adu, Victor Argo, Gino A...   
98  Al Pacino, Steven Bauer, Michelle Pfeiffer, Ma...   

                                          description  avg_vote    votes  \
1   The aging patriarch of an organized crime dyna...       9.2  1572674   
2   The early life and career of Vito Corleone in ...       9.0  1098714   
3   When the menace known as the Joker wreaks havo...       9.0  2241615   
4   A jury holdout attempts to prevent a miscarria...       8.9   668473   
6   The lives of two mob hitmen, a boxer, a gangst...       8.9  1780147   
9   The presidencies of Kenne

### 9. Extrageti deceniul cu cea mai mare medie a rating-ului filmelor.

*Hint: apply, groupby*

In [66]:
movies['decade'] = (movies['year'] // 10) * 10

decade_avg_rating = movies.groupby('decade')['avg_vote'].mean()

decade_with_highest_avg = decade_avg_rating.idxmax()

print(f"The decade with the highest rating mean is: {decade_with_highest_avg // 10}")

The decade with the highest rating mean is: 202


### 10. Care pereche actor-regizor are cele mai multe colaborari?

In [59]:
movies['directors_list'] = movies['director'].str.split(', ')

movies['actors_list'] = movies['actors'].str.split(', ')

collaborations = {}

for index, row in movies.iterrows():
    directors = row['directors_list']
    actors = row['actors_list']
    
    for director in directors:
        for actor in actors:
            if director != actor:
                if (director, actor) not in collaborations:
                    collaborations[(director, actor)] = 0
                collaborations[(director, actor)] += 1

max_collaborations = 0
most_collaborative_pair = ()
for pair, count in collaborations.items():
    if count > max_collaborations:
        max_collaborations = count
        most_collaborative_pair = pair

print(f"The most collaborative actor-director pair is: {most_collaborative_pair} with {max_collaborations} collaborations.")

The most collaborative actor-director pair is: ('Christopher Nolan', 'Michael Caine') with 5 collaborations.


Referinte bibliografice:

[1] https://docs.dask.org/en/stable/

[2] https://spark.apache.org/docs/latest/api/python/